org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

org.gradle.java.home=C:/Program Files/Microsoft/jdk-25.0.4.101-hotspot

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.64

mod_id=techtopia2
mod_name=TechTopia2
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.techtopia2